language: go
sudo: false

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
 - go get -u -v github.com/kisielk/errcheck
 - go get -u -v github.com/golang/lint/golint
 - go get -u -v honnef.co/go/tools/cmd/gosimple
 - go get -u -v honnef.co/go/tools/cmd/unused
 - go get -u -v github.com/mdempsky/unconvert
 - go get -u -v github.com/client9/misspell/cmd/misspell
 - go get -u -v github.com/gordonklaus/ineffassign
 - go get -u -v honnef.co/go/tools/cmd/staticcheck
 - go get -u -v github.com/fzipp/gocyclo

script:
 - chmod +x check.sh && chmod +x test.sh && ./check.sh && ./test.sh
